apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: repo-runner-petclinic-as
spec:
  template:
    spec:
      organization: nicks-world
      env: []
      dockerEnabled: false
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: repo-runner-petclinic-as-autoscaler
spec:
  scaleTargetRef:
    name: repo-runner-petclinic-as
  scaleDownDelaySecondsAfterScaleOut: 60
  minReplicas: 0
  maxReplicas: 3
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - nicks-world/petclinic