# Github Action Workflow: Build
# About this workflow: Example workflow that expects OPENJDK11, and Gradle for Build Tasks.
# What the workflow does: Take a Java/Gradle project, and run build tests for any commit to any branch.

name: build-petclinic
on: 
  workflow_dispatch:
    inputs:
      repo:
        description: 'repo: Repository to be built'
        required: true
      ref:
        description: 'ref: hash, tag, or branch in repo'
        required: true
        default: development


# TODO - on branch delete, check for namespace in "dev-cluster"
# Decide on 

jobs:
  build:
    runs-on: [ "pc" ]
    env:
      BUILD_REPO: ${{ github.event.inputs.repo }}
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ env.BUILD_REPO }}
        ref: ${{ github.event.inputs.ref }}
        path: ${{ env.BUILD_REPO }}
        token: ${{ secrets.CICD_TOKEN }}
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build with Gradle
      run: |
        ${GITHUB_WORKSPACE}/${BUILD_REPO}/gradlew build
