# Github Action Workflow: Build
# About this workflow: Example workflow that expects OPENJDK11, and Gradle for Build Tasks.
# What the workflow does: Take a Java/Gradle project, and run build tests for any commit to any branch.

name: build-petclinic
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'repo: Repository to be built'
        required: true
      ref:
        description: 'ref: hash, tag, or branch in repo'
        required: true
        default: development

jobs:
  build:
    runs-on: [ "pc" ]
    steps:
    - name: Setup environment
      run: |
        set -x
        echo "BUILD_REPO=${{ github.event.inputs.repo }}" >> ${GITHUB_ENV}
        echo "WORKING_DIR=${GITHUB_WORKSPACE}/${{ github.event.inputs.repo }}" >> ${GITHUB_ENV}

        echo "CICD_REPO_DIR=${GITHUB_WORKSPACE}/${GITHUB_REPOSITORY}" >> ${GITHUB_ENV}
        echo "CICD_REPO_SCRIPTS_DIR=${GITHUB_WORKSPACE}/${GITHUB_REPOSITORY}/scripts/build-to-dev" >> ${GITHUB_ENV}

        echo "CICD_NAMESPACE=pc-team-cicd" >> ${GITHUB_ENV}
        set +x
    - name: Checkout CICD Infra
      uses: actions/checkout@v2
      with:
        path: ${{ env.CICD_REPO_DIR }}
    - name: Checkout ${{ env.BUILD_REPO }}
      uses: actions/checkout@v2
      with:
        repository: ${{ env.BUILD_REPO }}
        ref: ${{ github.event.inputs.ref }}
        path: ${{ env.WORKING_DIR }}
        token: ${{ secrets.CICD_TOKEN }}
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        ${CICD_REPO_SCRIPTS_DIR}/build.sh
    - name: Test
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        ${CICD_REPO_SCRIPTS_DIR}/test.sh
    - name: Scan
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        ${CICD_REPO_SCRIPTS_DIR}/scan.sh
    - name: Build and Push Image
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        ${CICD_REPO_SCRIPTS_DIR}/build-image.sh
